### ISSUE TITLE
`Lspsaga code_action` failed

### ISSUE THREAD

**Issue by 0x00-ketsu** [nvimdev/lspsaga.nvim#1124]
### Describe the bug

![image](https://github.com/nvimdev/lspsaga.nvim/assets/16932133/6feb84f9-ac03-4dcd-94c7-fa1738bb08ae)
![image](https://github.com/nvimdev/lspsaga.nvim/assets/16932133/6f69ebe6-231f-4daf-8ec8-70359d96a1cf)

### Steps to reproduce

1. Create a project with git
2. nvim --clean -u min.lua main.go

**main.go**

```golang
package main

import "fmt"

func main() {
	fmt.Println("Hello, World!")
}
```

**min.lua**

```lua
local api = vim.api

api.nvim_command('set nu')
api.nvim_command('set relativenumber')

-- Plugins
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system(
      {
        'git', 'clone', '--filter=blob:none', 'https://github.com/folke/lazy.nvim.git',
        '--branch=stable', -- latest stable release
        lazypath
      }
  )
end
vim.opt.rtp:prepend(lazypath)

-- Example using a list of specs with the default options
vim.g.mapleader = ',' -- Make sure to set `mapleader` before lazy so your mappings are correct

require('lazy').setup(
    {
      -- LuaFormatter off
      {'ellisonleao/gruvbox.nvim', config = function()
          require('gruvbox').setup {}
        end
      },
      {
        'hrsh7th/nvim-cmp',
        event = 'InsertEnter',
        config = function()
          require('cmp').setup {}
        end,
        dependencies = {
          {'hrsh7th/cmp-nvim-lsp'},
        },
      },
      {
        'neovim/nvim-lspconfig',
        config = function()
          require'lspconfig'.pyright.setup {}
          require'lspconfig'.gopls.setup {}
        end
      },
      {
        'williamboman/mason.nvim',
        config = function()
          require('mason').setup()
        end
      },
      {'williamboman/mason-lspconfig.nvim'},
      {
        'jose-elias-alvarez/null-ls.nvim',
        config = function()
          local null_ls = require('null-ls')
          local code_actions = null_ls.builtins.code_actions
          local diagnostics = null_ls.builtins.diagnostics
          null_ls.setup {
          sources = {
            code_actions.gitsigns,
            diagnostics.golangci_lint
          }
        }
        end,
        dependencies = {{'nvim-lua/plenary.nvim'}}
      },
      -- LuaFormatter on

      {
        'lewis6991/gitsigns.nvim',
        lazy = true,
        event = {'BufRead', 'BufNewFile'},
        config = function()
          require('gitsigns').setup {}
        end,
        dependencies = {'nvim-lua/plenary.nvim'}
      },
      {
        'glepnir/lspsaga.nvim',
        event = 'BufRead',
        config = function()
          require('lspsaga').setup({})
        end,
        dependencies = {{'nvim-tree/nvim-web-devicons'}, {'nvim-treesitter/nvim-treesitter'}}
      }
    }
)
```

### Expected behavior

Can do code actions. 

### Neovim version (nvim -v)

0.9.1

### lspsaga commit

8a05cb1

### Terminal name/version

iterm2 3.4.19

**Comment by glepnir** [comment]
wired .I can't reproduce ..

**Comment by 0x00-ketsu** [comment]
`gitsigns.nvim` commit : `dc2962f` (latest)

**Comment by eXvimmer** [comment]
Did anyone find a solution for this?
Should I open a new issue in `gitsigns.nvim` repo?

**Comment by glepnir** [comment]
this issue has been fixed

**Comment by eXvimmer** [comment]
I have updated to the latest version.
I still get the exact same behavior.

**Comment by glepnir** [comment]
What do you mean?

**Comment by eXvimmer** [comment]
If you look at the top picture, instead of showing code actions for fixing problems (like auto import, etc.), it only shows  `gitsigns.nvim` commands.

**Comment by glepnir** [comment]
Why show auto import?there is no lsp actions it has import fmt?

**Comment by eXvimmer** [comment]
It was just an example. If there's an error, and you try to do `Lspsaga diagnostic_jump_next`, it won't show the options for code action. It only shows `gitsigns` actions.

**Comment by eXvimmer** [comment]
So here's a simple example. It says fix available, but doesn't show anything.

[Screencast from 11-07-23 04:07:22.webm](https://github.com/nvimdev/lspsaga.nvim/assets/30720669/5cc3e675-ee59-4400-bc67-5e5fcb39d029)

**Comment by glepnir** [comment]
I think igot your point ，test later reopen

**Comment by eXvimmer** [comment]
thanks

**Comment by glepnir** [comment]
I think igot your point ，test later reopendoes vim.lsp.buf.code action has output?

**Comment by eXvimmer** [comment]
It works now. Thanks

**Comment by eXvimmer** [comment]
Hi.
There's another bug.
After fixing a problem with code actions (like choosing option 1), if you move your cursor and keep pressing the same number (e.g., 1), it will keep inserting the same fix to the document.
