### ISSUE TITLE
Error when using hover after diagnostic_jump

### ISSUE THREAD

**Issue by fent** [nvimdev/lspsaga.nvim#1244]
### Describe the bug

```
Error detected while processing CursorMoved Autocommands for "<buffer=1>":
Error executing lua callback: /tmp/lazy/plugins/lspsaga.nvim/lua/lspsaga/util.lua:95: E31: No such mapping
stack traceback:
        [C]: in function 'nvim_buf_del_keymap'
        /tmp/lazy/plugins/lspsaga.nvim/lua/lspsaga/util.lua:95: in function 'delete_scroll_map'
        /tmp/lazy/plugins/lspsaga.nvim/lua/lspsaga/hover.lua:168: in function </tmp/lazy/plugins/lspsaga.nvim/lua/lspsaga/hover.lua:166>
```

### Steps to reproduce

1. run `:Lspsaga diagnostic_jump_next` to jump to a diagnostic. you can create a syntax error if the file has no diagnostics
2. be sure not to move the cursor after running `diagnostic_jump_next`
3. run `:Lspsaga hover`. there should now be 2 floating windows drawn. the diagnostic window, and the hover window
4. move the cursor
5. see error

if you then use the hover function again, it will display a window and jump into it, as if you ran hover twice

### Expected behavior

for there to not be an error, and possibly to close the diagnostic window before displaying the hover window. although that's a design choice

### Neovim version (nvim -v)

0.9.0

### lspsaga commit

58cbf44

### Terminal name/version

Alacritty 0.11.0

**Comment by fent** [comment]
that was fast. but now I'm getting this new error whenever I run `hover` no matter if after/before `diagnostic_jump_next`

```
Error executing Lua callback: /tmp/lazy/plugins/lspsaga.nvim/lua/lspsaga/hover.lua:326: module 'diagnostic' not found:
``

**Comment by glepnir** [comment]
fixed.

**Comment by fent** [comment]
thanks for the quick reply. but unfortunately i'm still seeing the original error when i try the steps above to reproduce

**Comment by glepnir** [comment]
update and retry

**Comment by fent** [comment]
awesome it works! thanks again!

**Comment by farzadmf** [comment]
@glepnir this issue seems to be happening again for me 🙁 : when I hover (using `K`) and then I want to close the hover (with `K` again), I'm getting the error

**Comment by glepnir** [comment]
emm create a new issue with reproduce step.

**Comment by farzadmf** [comment]
@glepnir created #1451 ; I'd appreciate if you take a look

Thank you
